USE [ATA]
GO

DBCC CHECKIDENT (Examiners, RESEED, 0)

INSERT INTO [dbo].[Examiners] ([FirstName],[Surname],[Phone])
VALUES

('Albiero','Giancarlo',''),
('Assettati','Giovanni',''),
('Borrini','Davide',''),
('Boscherini','Elisa',''),
('Cavicchi','Fulvio',''),
('Crowly','Monica',''),
('D’Alessandro','Sebastiano',''),
('Debernardis','Andrea',''),
('Deitinger','Laura',''),
('Donato','Silvio',''),
('Ehrlich','Jonathan',''),
('Garzulli','Serena',''),
('Gentili','Luca',''),
('Grassi','Luca',''),
('Loiodice','Cinzia',''),
('Manna','Francesca',''),
('Melani','Marco',''),
('Nervi','Claudio',''),
('Nucciarelli','Alberto',''), 
('Ollino','Giulia',''),
('Rebaudo','Enrico',''),
('RIO','Giacomo',''),
('Sciolari','Alessandro',''),
('Sperati','Maurizio',''),
('Temporelli','Valentina',''),
('Teti','Francesco',''),
('Zanetti','Andrea',''),
('Aversa','Paolo',''),
('Manna','Francesca',''),
('Carraro','Gilles',''),
('Pesare','Salvatore',''),

('Agricola','Rocco',''),
('Andreoletti','Fabio',''),
('Annicchiarico','Claudio',''),
('Anzioso','Franco',''),
('Badia','Tiziano',''),
('Battimazza','Alessio',''),
('Brusaglino','Giampiero',''),
('Cairola','Marco',''),
('Campanale','Carlo',''),
('Cantella','Andrea',''),
('Ceriello','Giovanni',''),
('Cinà Alessandro','Pietro',''),
('Cipelli','Marco',''),
('Coeli','Paolo',''),
('Colombo','Maurizio',''),
('Concari','Nando',''),
('Cuttica','Massimo',''),
('Dallara','Gian Paolo',''),
('Danisi','Giacomo',''),
('Danna','Fabio',''),
('De Lauretisi','Antonio',''),
('De Vita','Luca',''),
('Di Rosa','Giuseppe',''),
('Di Vinci','Andrea',''),
('Esposto','Daniele',''),
('Esposto','Filippo',''),
('Ferrara','Ferdinando',''),
('Fregonese','Raffaele',''),
('Frumusa','Vincenzo',''),
('Gamberini','Giorgio',''),
('Giansetto','Giacomo',''),
('Gokce','Can',''),
('Guccione','Stefano',''),
('Laviola','Francesco',''),
('Lilli','Francesco',''),
('Lombardi','Emanuele',''),
('Maceratini','Roberto',''),
('Manzali','Claudio',''),
('Monti','Francesco',''),
('Morsone','Giulio',''),
('Nardone','Miriam',''),
('Oceano','Andrea',''),
('Oest','Holger',''),
('Ollino','Paolo',''),
('Paiardi','Marco',''),
('Poerio','Nicola',''),
('Ricci','Claudio',''),
('Ricci','Roberto',''),
('Rivagli','Luca',''),
('Savio','Walter',''),
('Sbrosi','Marco',''),
('Tampolli','Raffaele',''),
('Toscano','Gianluca',''),
('Toso','Andrea',''),
('Vezza','Davide',''),
('Viola','Gianfabio','')
				
				

GO


