// <auto-generated />
namespace ATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20210912_Fase4AddingFinals : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20210912_Fase4AddingFinals));
        
        string IMigrationMetadata.Id
        {
            get { return "202109121459308_20210912_Fase4AddingFinals"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
