// <auto-generated />
namespace ATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20210825AddStage2Upd2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20210825AddStage2Upd2));
        
        string IMigrationMetadata.Id
        {
            get { return "202108251700400_2021.08.25.AddStage2Upd2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
