// <auto-generated />
namespace ATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ATA_2022_Stage3_upd1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ATA_2022_Stage3_upd1));
        
        string IMigrationMetadata.Id
        {
            get { return "202207061530534_ATA_2022_Stage3_upd1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
