// <auto-generated />
namespace ATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20220513Stage2_upd1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20220513Stage2_upd1));
        
        string IMigrationMetadata.Id
        {
            get { return "202205131401598_20220513-Stage2_upd1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
