// <auto-generated />
namespace ATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20220516Stage2_upd2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20220516Stage2_upd2));
        
        string IMigrationMetadata.Id
        {
            get { return "202205161035494_20220516-Stage2_upd2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
