// <auto-generated />
namespace ATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ATA_2023_Stage3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ATA_2023_Stage3));
        
        string IMigrationMetadata.Id
        {
            get { return "202306270939161_ATA_2023_Stage3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
