// <auto-generated />
namespace ATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ATA_2023_addFinConcept : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ATA_2023_addFinConcept));
        
        string IMigrationMetadata.Id
        {
            get { return "202305161052535_ATA_2023_addFinConcept"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
