// <auto-generated />
namespace ATA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ATA2024_content : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ATA2024_content));
        
        string IMigrationMetadata.Id
        {
            get { return "202406101045562_ATA2024_content"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
